#!/usr/bin/env python3
"""
Build-time CurseForge API Key Obfuscation Script.

Reads the plaintext API key and a salt, XOR-encrypts the key with the salt,
and writes a C++ header file containing the encrypted key as a byte array
with the salt appended. The runtime decryption XORs the encrypted bytes
back using the salt at the point of API call.

Usage:
    python obfuscate_key.py <api_key> <salt_hex> <output_path>
"""
import sys
import os


def xor_encrypt(key: str, salt_hex: str) -> tuple:
    """XOR encrypt the key bytes with the salt bytes."""
    salt = bytes.fromhex(salt_hex) if salt_hex else os.urandom(32)
    salt_bytes = salt[:32]  # Use at most 32 bytes of salt
    key_bytes = key.encode('utf-8')

    encrypted = bytearray()
    for i, b in enumerate(key_bytes):
        encrypted.append(b ^ salt_bytes[i % len(salt_bytes)])

    return bytes(encrypted), salt_bytes


def generate_header(encrypted_key: bytes, salt: bytes, has_key: bool) -> str:
    """Generate the C++ header content."""
    enc_hex = ', '.join(f'0x{b:02x}' for b in encrypted_key)
    salt_hex = ', '.join(f'0x{b:02x}' for b in salt)
    key_len = len(encrypted_key)

    return f"""#ifndef API_KEYS_H
#define API_KEYS_H

// AUTO-GENERATED by obfuscate_key.py at build time.
// Do NOT check this file into version control.

#include <array>
#include <cstdint>

namespace ApiKeys {{

// Encrypted CurseForge API key (XOR'd with salt)
static constexpr std::array<uint8_t, {key_len}> kCurseForgeKeyEncrypted = {{
    {enc_hex}
}};

// XOR salt used for decryption
static constexpr std::array<uint8_t, {len(salt)}> kCurseForgeSalt = {{
    {salt_hex}
}};

// Returns true if a valid CurseForge API key was injected at build time
inline bool HasCurseForgeKey() {{ return {str(has_key).lower()}; }}

}}

#endif // API_KEYS_H
"""


def main():
    if len(sys.argv) < 4:
        print("Usage: obfuscate_key.py <api_key> <salt_hex> <output_path>")
        sys.exit(1)

    api_key = sys.argv[1]
    salt_hex = sys.argv[2]
    output_path = sys.argv[3]

    has_key = len(api_key) > 0 and api_key != ""
    if not has_key:
        # Write stub
        header = """#ifndef API_KEYS_H
#define API_KEYS_H
// AUTO-GENERATED - Empty key (CF_API_KEY not set at build time)
#include <array>
#include <cstdint>
namespace ApiKeys {
static constexpr std::array<uint8_t, 0> kCurseForgeKeyEncrypted = {};
static constexpr std::array<uint8_t, 4> kCurseForgeSalt = {0,0,0,0};
inline bool HasCurseForgeKey() { return false; }
}
#endif // API_KEYS_H
"""
    else:
        encrypted, salt = xor_encrypt(api_key, salt_hex)
        header = generate_header(encrypted, salt, True)

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header)

    print(f"[obfuscate_key] Written to {output_path} (has_key={has_key})")


if __name__ == '__main__':
    main()